name: Build iOS Server (IPA)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build App
        run: |
          xcodebuild clean build \
            -project "OcrServer.xcodeproj" \
            -alltargets \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CONFIGURATION_BUILD_DIR=$PWD/build

      - name: Package into IPA
        run: |
          mkdir -p Payload
          cp -r build/OcrServer.app Payload/
          zip -qr OcrServer.ipa Payload



      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OcrServer-App
          path: OcrServer.ipa
          retention-days: 5
